### ISSUE TITLE
Integration with a 4Panel Client

### ISSUE THREAD

**Issue by marysiamzawka** [TNG-dev/tachi-server#400]
This may be possible, given that at one point KTv1 had Etterna support.

While SM5 cannot talk with a network service on its own, it has been achieved by using an external tool and a suitable theme (namely [Groovestats Launcher](https://github.com/GrooveStats/gslauncher))

Groovestats itself has been up for over 15 years now, but it's showing its age. Besides, it would be fun to have support for more songpacks (and for Beginner difficulties too!)

**Comment by zkldi** [comment]
Thought about this more and the state of SM5 makes me not want to integrate it at all.

If you're reading this, I'm absolutely willing to integrate with any sort of ITG-esque client because I think it'd be **really cool**. However, SM5 is an absolutely unusable state, it doesn't even implement proper chart hashing, and the codebase has been stagnant and filled with useless bloat for years. Themes have done all the progress in stepmania since sm3.95, and those are still limited.

If you're reading this and you really want to help, make a 4panel client that doesn't suck. Seriously. I'll throw all my weight behind any sort of IR integration.

**Comment by zkldi** [comment]
Themes do most of the heavy lifting, so I'm going to throw a good effort behind the community and theme our way out of this one.

**Comment by zkldi** [comment]
Nevermind, I'm against this idea again.
