### ISSUE TITLE
support usc permissive gauge

### ISSUE THREAD

**Issue by ereti** [TNG-dev/tachi-server#528]
gaugetype 2

**Comment by zkldi** [comment]
The best way to do this is to just set all scores with gaugetype 2 to FAILED. this is counterintuitive technically, but nobody cares about permissive clears, right?

This is also 1:1 with the behaviour of sdvx, so I think I might just make all of these scores fails rather than adding a new lamp and having to reshift all the scores on the site.

**Comment by zkldi** [comment]
Yeah, going to make this a fail, permissive clear isn't an interesting metric by any means and only applies to a very small subset of charts.

**Comment by zkldi** [comment]
This has landed in develop but it's wrong. We need to add a PERMISSIVE CLEAR lamp so we can infer whether scores were on permissive or not (for imgscores). This will require some tachi-common fiddling.

**Comment by zkldi** [comment]
update, `gaugeMod` in usc scores declares this properly. We'll mutate that in tachi-common and re-resolve this issue.
