### ISSUE TITLE
WACCA Support

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-server#598]
cg505 appears to be championing this quite a bit as an idea, and there's no reason we can't. We'll just have to sit down at some point and talk about how the game works and then parse some chart data. Sounds easy enough. Which means it'll be fiendishly difficult.

**Comment by cg505** [comment]
I will add more info later.

**Comment by cg505** [comment]
Each song has 3-4 difficulties, which are NORMAL, HARD, EXPERT, and optionally INFERNO. Levels range from 1 to 14, with + difficulties between (e.g. 10+). I don't think there are any + levels for NORMAL or for 1-4. (There is a HARD 5+.)
Each chart has a "chart constant" which is an internal rating such as 10.2. These correspond to levels: .0-.6 correspond to the base level, and .7-.9 correspond to the + level. (e.g. constant 13.6 is level 13, but constant 13.7 is level 13+). The internal constant is not exposed but used for rating calculation. I believe the chart constants for all EXPERT and INFERNO charts have been determined, but I'm not sure about NORMAL and HARD.

Suggested schemas:
song.data
```
type WaccaSongData = { genre: string; displayVersion: string | null };
```
chart
```
// This can be used for GPTSupportedVersions theoretically, but we also need it for releaseVersion.
type WaccaVersions = "WACCA" | "WACCA S" | "WACCA Lily" | "WACCA Lily R" | `WACCA Reverse"
type WaccaChartData = { releaseVersion: WaccaVersions };
```

Scoring is percent-based out of 1 000 000. Scoring details can be found here: https://wiki.misslessfighters.club/wiki/Game_Mechanics#Scoring. As you can see, grades are entirely score/percent based.

There are 5 lamps: FAILED, CLEAR, MISSLESS (which means 5 misses or less lol), FULL COMBO, and ALL MARVELOUS (same as MASTER grade). The wiki link has the last three but don't forget about FAILED and CLEAR. There's no hard gauge or anything.

Suggested schemas:
```
type WaccaLamps = "FAILED" | "CLEAR" | "MISSLESS" | "FULL COMBO" | "ALL MARVELOUS";
type WaccaGrades = "D" | "C" | "B" | "A" | "AA" | "AAA" | "S" | "S+" | "SS" | "SS+" | "SSS" | "SSS+" | "MASTER";
type WaccaJudges = "marvelous" | "great" | "good" | "miss";
// n.b. fast/slow should be renamed to early/late since that's what it's called in every game except iidx and ddr
type WaccaHitMeta = BASE_VALID_HIT_META;
type WaccaScoreMeta = { mirror: boolean | null };
```

Dans are called "STAGE UP" and involve playing playing 3 consecutive charts without losing too many lives. https://wacca.fandom.com/wiki/Stage_Up Stages go from I to XIV. Depending on how many lives you have left at the end, you can get a Blue, Silver, or Gold colored clear for the stage.
I don't think Blue/Silver/Gold should be considered separate stages - it's more like gold wings/halo in sdvx.

The main rating mechanism is simply called Rate. There are classes based on Rate, indicated on the machine by the color of the numbers. An individual Rate chart is calculated as follows:
Score is converted to a value called the "score coefficient" according to this table
```
0 ~ 800000               1
850000                   1.5
900000                   2
920000                   2.5
940000                   2.75
950000                   3
960000                   3.25
970000                   3.5
980000                   3.75
990000 ~ 1000000         4
```
then simply
```
rate = score coefficient * chart constant (internal rating)
```
Note that this means there's no difference in Rate between a 980000 and a 989999, or between a 990000 and a 1000000.
Overall profile Rate works kind of similarly to Gitadora, except instead of "Hot" it prioritizes songs released in the most recent version of the game. It is the sum of the top 15 song Rates from WACCA Reverse, plus the sum of the top 35 songs from all other versions. Also, apparently you can only receive Rate from one chart per song - that is, if your Rate for the EXPERT chart is better than your Rate for the INFERNO, the INFERNO can't be counted in the sums.
I would also propose adding a `NaiveRate` statistic that just sums your top 50 charts regardless of song or version.
Rate color classes are:
```
   0-299  Ash
 300-599  Navy
‌‌ 600-999  Yellow
1000-1299 Red
1300-1599 Purple
1600-1899 Blue
1900-2199 Silver
2200-2499 Gold
2500+     Rainbow
```

The user also has a "level". No one cares about this, it is essentially a playcount tracker.

**Comment by cg505** [comment]
In terms of getting data, there is this tool https://github.com/shimmand/waccaSupportTools which includes chart data (have not verified its completeness) and a javascript tool for scraping score data from the website, which we can probably adapt to meet our needs.
In general, the website provides PBs and full data on your last 50 plays, which we should be able to get. waccaSupportTools works by using a bookmarklet that fetches and runs javascript from their server, which is kinda spicy. I think the ideal solution here would be a userscript, but in general mobile support will probably be poor. We can reference their code as a base at least.

**Comment by cg505** [comment]
Normal/Hard support isn't available from waccaSupportTools at the moment, and I don't know of any other source. It may be available in the future. https://twitter.com/shimmand/status/1472421860206088197 in the meantime, it's not unreasonable to just use the base level as the chart constant (e.g. Hard 6 is just 6.0).

**Comment by zkldi** [comment]
Although #604 has just been merged, we'll still need some backend data for this - the songs and charts. I think these can be fetched from that csv file you posted before, so I guess we'll just have to get around to that.

**Comment by zkldi** [comment]
Songs and charts have just been added to tachi-database-seeds. Looks like we're green on this.

**Comment by zkldi** [comment]
Aaaand we're live.

**Comment by zkldi** [comment]
And by live i mean live on staging. But this is good to go.
